### PR TITLE
Add CVE due date #91

### PR DESCRIPTION
**Pull request by gytis**
@metacosm or @jacobdotcosta would you mind trying this out? I'm not able to authenticate myself with JIRA.

### CODE REVIEW

**Review by metacosm — APPROVED** [review]
LGTM

**Comment by gytis** [comment]
Sure sure, it's not urgent.

**Review by metacosm — CHANGES_REQUESTED** [review]
Actually, upon further review, I'd like some changes. 

- Due date should be an Issue directly so that we can get the same kind of reporting on all issues, not only CVEs
- The text only report should also include that information and we should look into making the status generation for a given issue shared between the MD and text versions.

**Comment by gytis** [comment]
@metacosm I've joined both ASCII and MD report generation into a common `ReportingService` (renamed from a `CVEReportingServie`)

**Review by metacosm — APPROVED** [review]
Moving due date to issue could be made in a subsequent PR.

**Comment by gytis** [comment]
If you prefer I could rename the commit (I forgot before) to something like `Add issue due date` instead of `Add CVE due date`

**Comment by gytis** [comment]
Or do you prefer me to split them altogether into service refactor commit/pr and due date commit/pr?

**Comment by metacosm** [comment]
Sorry missed the fact that you moved the code to Issue, so it's all good for me!

**Pull request merged**
